import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "../lib/supabase";

const QUESTIONS = ["İlk evcil hayvanının adı nedir?", "İlkokulunun adı nedir?", "En sevdiğin öğretmenin adı nedir?"];

export default function AuthScreen() {
  const [mode, setMode] = useState<"login" | "register" | "recover">("login");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [question, setQuestion] = useState(QUESTIONS[0]); const [answer, setAnswer] = useState("");
  const [loadedQuestion, setLoadedQuestion] = useState(""); const [busy, setBusy] = useState(false);
  async function submit() {
    if (!email.trim()) return Alert.alert("E-posta gerekli", "E-posta adresini gir.");
    try { setBusy(true);
      if (mode === "login") { const { error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (error) throw error; }
      else if (mode === "register") { if (password.length < 8 || !answer.trim()) throw new Error("Şifren en az 8 karakter, güvenlik cevabı zorunludur."); const { error } = await supabase.auth.signUp({ email: email.trim(), password, options: { data: { security_question: question, security_answer: answer } } }); if (error) throw error; Alert.alert("Kayıt tamamlandı", "E-posta doğrulama bağlantısını açtıktan sonra giriş yapabilirsin."); setMode("login"); }
      else if (!loadedQuestion) { const { data, error } = await supabase.rpc("get_security_question", { p_email: email.trim() }); if (error || !data) throw new Error("Bu e-posta için güvenlik sorusu bulunamadı."); setLoadedQuestion(data); }
      else { const { data, error } = await supabase.rpc("verify_security_answer", { p_email: email.trim(), p_answer: answer }); if (error || !data) throw new Error("Güvenlik cevabı eşleşmedi."); const { error: resetError } = await supabase.auth.resetPasswordForEmail(email.trim()); if (resetError) throw resetError; Alert.alert("Bağlantı gönderildi", "Şifre yenileme bağlantısı e-posta adresine gönderildi."); setMode("login"); setLoadedQuestion(""); }
    } catch (error) { Alert.alert("İşlem yapılamadı", error instanceof Error ? error.message : "Tekrar dene."); } finally { setBusy(false); }
  }
  return <ScrollView contentContainerStyle={styles.screen}><View style={styles.card}><Text style={styles.logo}>Bütçe</Text><Text style={styles.title}>{mode === "login" ? "Giriş yap" : mode === "register" ? "Hesap oluştur" : "Şifremi unuttum"}</Text><Text style={styles.subtitle}>Verilerin yalnızca kendi hesabında saklanır.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="E-posta adresi" placeholderTextColor="#94A3B8" style={styles.input}/>{mode !== "recover" && <TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Şifre" placeholderTextColor="#94A3B8" style={styles.input}/>} {mode === "register" && <><Text style={styles.label}>Güvenlik sorusu</Text>{QUESTIONS.map((item) => <Pressable key={item} onPress={() => setQuestion(item)} style={[styles.question, question === item && styles.questionActive]}><Text style={styles.questionText}>{item}</Text></Pressable>)}<TextInput value={answer} onChangeText={setAnswer} placeholder="Cevabın" placeholderTextColor="#94A3B8" style={styles.input}/></>}{mode === "recover" && loadedQuestion && <><Text style={styles.label}>{loadedQuestion}</Text><TextInput value={answer} onChangeText={setAnswer} placeholder="Cevabın" placeholderTextColor="#94A3B8" style={styles.input}/></>}<Pressable disabled={busy} onPress={submit} style={styles.submit}><Text style={styles.submitText}>{busy ? "Bekle..." : mode === "recover" && !loadedQuestion ? "Soruyu göster" : mode === "recover" ? "Şifre yenileme bağlantısı gönder" : mode === "login" ? "Giriş yap" : "Kayıt ol"}</Text></Pressable><View style={styles.links}>{mode !== "login" && <Pressable onPress={() => { setMode("login"); setLoadedQuestion(""); }}><Text style={styles.link}>Girişe dön</Text></Pressable>}{mode === "login" && <><Pressable onPress={() => setMode("register")}><Text style={styles.link}>Kayıt ol</Text></Pressable><Pressable onPress={() => setMode("recover")}><Text style={styles.link}>Şifremi unuttum</Text></Pressable></>}</View></View></ScrollView>;
}
const styles = StyleSheet.create({ screen:{flexGrow:1,backgroundColor:"#F7F8FA",justifyContent:"center",padding:24},card:{alignSelf:"center",width:"100%",maxWidth:420,backgroundColor:"#FFF",borderRadius:20,padding:24,borderWidth:1,borderColor:"#E2E8F0"},logo:{fontSize:26,fontWeight:"900",color:"#17202A"},title:{marginTop:24,fontSize:24,fontWeight:"900",color:"#17202A"},subtitle:{marginTop:6,color:"#64748B"},input:{minHeight:50,borderWidth:1,borderColor:"#E2E8F0",borderRadius:12,paddingHorizontal:14,marginTop:12,color:"#17202A"},label:{marginTop:16,fontWeight:"800",color:"#17202A"},question:{marginTop:8,padding:11,borderWidth:1,borderColor:"#E2E8F0",borderRadius:10},questionActive:{borderColor:"#2563EB",backgroundColor:"#EFF6FF"},questionText:{fontSize:12,color:"#334155"},submit:{minHeight:52,marginTop:20,borderRadius:12,backgroundColor:"#16A34A",alignItems:"center",justifyContent:"center"},submitText:{color:"#FFF",fontWeight:"900"},links:{marginTop:18,flexDirection:"row",justifyContent:"space-between"},link:{color:"#2563EB",fontWeight:"800",fontSize:13} });
